### ISSUE TITLE
Should not link to Web3 Foundation Twitter

### ISSUE THREAD

**Issue by mmagician** [jackson-harris-iii/staking-rewards-viewer#21]
Please remove the link to https://twitter.com/web3foundation

Also, the link at the bottom of the page at "a web3 foundation open source contribution" should not lead to [the grants page](https://web3.foundation/grants/).

The above two give off the impression that this tool is **built by the Web3 Foundation**. That's not the case, since we simply support the development of open source code.

Feel free to replace the Twitter link with your own Twitter account.
Regarding the second link, you can integrate a badge instead, once your milestone has been merged. See [badge guidelines here](https://github.com/w3f/Grants-Program/blob/master/docs/grant-badge-guidelines.md).

Thanks for cooperation!

**Comment by jackson-harris-iii** [comment]
@mmagician can the badge include a link?

**Comment by mmagician** [comment]
@jackson-harris-iii Please remove that link.
